export const CONTACT_DUMMY_DATA=[
    {
        "contactId": 100707,
        "firstName": "Andrew",
        "lastName": "Napier",
        "title": "HERS Rater",
        "streetAddress": "8552 N. EMPIRE AVE",
        "city": "CITRUS SPRINGS",
        "postCode": "34433",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"}]"
    },
    {
        "contactId": 101720,
        "firstName": "Collin",
        "lastName": "Owens",
        "title": "Filed Consultant",
        "streetAddress": "",
        "city": "Sarasota",
        "postCode": "34237",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"}]"
    },
    {
        "contactId": 100709,
        "firstName": "Corey",
        "lastName": "Moore",
        "title": "HERS Rater",
        "streetAddress": "4022 LANDOVER BLVD",
        "city": "SPRING HILL",
        "postCode": "34609",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"}]"
    },
    {
        "contactId": 100710,
        "firstName": "Corey",
        "lastName": "Sirico-QB",
        "title": "HERS Rater",
        "streetAddress": "24467 HIDDEN WOODS ROAD",
        "city": "BROOKSVILLE",
        "postCode": "34601",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"ESTAR-MF\"},{\"Skill\":\"HVAC-GRADING\"},{\"Skill\":\"INDOOR AIR+\"},{\"Skill\":\"QA QCCHECK\"}]"
    },
    {
        "contactId": 100714,
        "firstName": "Gabriel",
        "lastName": "Barzana-Santiago",
        "title": "HERS Rater",
        "streetAddress": "26949 JUNIPER BAY DRIVE",
        "city": "WESLEY CHAPEL",
        "postCode": "33544",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"HVAC-GRADING\"},{\"Skill\":\"INDOOR AIR+\"}]"
    },
    {
        "contactId": 100716,
        "firstName": "Hugh",
        "lastName": "Coyne-QB",
        "title": "HERS Rater",
        "streetAddress": "619 SALLY LANE S #5",
        "city": "CLEARWATER",
        "postCode": "33756",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"FGBC\"},{\"Skill\":\"QA QCCHECK\"}]"
    },
    {
        "contactId": 100717,
        "firstName": "Irving",
        "lastName": "Serra-Rios-QB",
        "title": "HERS Rater",
        "streetAddress": "15420 LIVINGSTON AVE",
        "city": "LUTZ",
        "postCode": "33615",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"ESTAR-MF\"},{\"Skill\":\"HVAC-GRADING\"},{\"Skill\":\"INDOOR AIR+\"},{\"Skill\":\"QA QCCHECK\"}]"
    },
    {
        "contactId": 100719,
        "firstName": "Jeff",
        "lastName": "Paquette-QB",
        "title": "HERS Rater",
        "streetAddress": "",
        "city": "Riverview, FL ",
        "postCode": "33579",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"QA QCCHECK\"}]"
    },
    {
        "contactId": 56377,
        "firstName": "Jeremy",
        "lastName": "Hook",
        "title": null,
        "streetAddress": "351 BEACHWOOD AVE",
        "city": "LEHIGH ACRES",
        "postCode": "33936",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"FGBC\"},{\"Skill\":\"QA QCCHECK\"}]"
    },
    {
        "contactId": 101014,
        "firstName": "Jeremy",
        "lastName": "Olsen",
        "title": "",
        "streetAddress": "1116 WEST CARMEN ST 604",
        "city": "TAMPA",
        "postCode": "33606",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"INDOOR AIR+\"}]"
    },
    {
        "contactId": 100721,
        "firstName": "Jose",
        "lastName": "Rosario-QB",
        "title": "HERS Rater",
        "streetAddress": "18172 PORFIRIO PL",
        "city": "SPRING HILL",
        "postCode": "34610",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"ESTAR-MF\"},{\"Skill\":\"FGBC\"},{\"Skill\":\"QA QCCHECK\"}]"
    },
    {
        "contactId": 100722,
        "firstName": "Justin",
        "lastName": "Ehrenpreis",
        "title": "HERS Rater",
        "streetAddress": "11500 N  DALE MABRY HWY",
        "city": "TAMPA",
        "postCode": "33618",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"QA QCCHECK\"}]"
    },
    {
        "contactId": 100983,
        "firstName": "Kayla",
        "lastName": "Billings",
        "title": "Field Consultant",
        "streetAddress": "2348 BOUGAINVILLEA ST",
        "city": "SARASOTA",
        "postCode": "34239",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"INDOOR AIR+\"}]"
    },
    {
        "contactId": 56370,
        "firstName": "Kevin",
        "lastName": "Buttrum",
        "title": "Field Consultant",
        "streetAddress": "2418 CHANDLER AVE",
        "city": "FORT MYERS",
        "postCode": "33907",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"QA QCCHECK\"}]"
    },
    {
        "contactId": 100733,
        "firstName": "Mai",
        "lastName": "Yang-QB",
        "title": "HERS Rater",
        "streetAddress": "7501 PORTOSUENO AVE",
        "city": "BRADENTON",
        "postCode": "34209",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"QA QCCHECK\"}]"
    },
    {
        "contactId": 56354,
        "firstName": "Michael",
        "lastName": "Ferguson",
        "title": "FC",
        "streetAddress": "2348 BOUGAINVILLEA ST",
        "city": "SARASOTA",
        "postCode": "34239",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"ESTAR-MF\"},{\"Skill\":\"HVAC-GRADING\"},{\"Skill\":\"POST-INSULATION\"},{\"Skill\":\"FGBC\"},{\"Skill\":\"FL WATER STAR\"},{\"Skill\":\"QA QCCHECK\"},{\"Skill\":\"M2QC (Cert IR, Predrywall, Trim IR, Annual)\"},{\"Skill\":\"QA RESIDENTIAL\"},{\"Skill\":\"QA COMMERCIAL\"},{\"Skill\":\"DRONE\"}]"
    },
    {
        "contactId": 100725,
        "firstName": "Nicholas",
        "lastName": "Seabolt",
        "title": "HERS Rater",
        "streetAddress": "4706 LIMERICK DRIVE",
        "city": "TAMPA",
        "postCode": "33610",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"}]"
    },
    {
        "contactId": 56387,
        "firstName": "Raymond",
        "lastName": "Butterfield",
        "title": "Rating Field Inspector",
        "streetAddress": "3750 ALLENWOOD STREET",
        "city": "SARASOTA",
        "postCode": "34232",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"ESTAR-MF\"},{\"Skill\":\"DOE NZ\"},{\"Skill\":\"HVAC-GRADING\"},{\"Skill\":\"INDOOR AIR+\"},{\"Skill\":\"QA QCCHECK\"},{\"Skill\":\"M2QC (Cert IR, Predrywall, Trim IR, Annual)\"}]"
    },
    {
        "contactId": 100727,
        "firstName": "Reece",
        "lastName": "Norbeck-QB",
        "title": "HERS Rater",
        "streetAddress": "3001 SE LAKE WEIR AVE APT 904",
        "city": "OCALA",
        "postCode": "34471",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"HVAC-GRADING\"},{\"Skill\":\"INDOOR AIR+\"},{\"Skill\":\"QA QCCHECK\"}]"
    },
    {
        "contactId": 100705,
        "firstName": "Zander",
        "lastName": "Harris",
        "title": "HERS Rater",
        "streetAddress": "582 NE 5TH STREET",
        "city": "CAPE CORAL",
        "postCode": "33909",
        "state": "FL",
        "countryCode": "US",
        "primaryMarkets": "[{\"Market\":\"Tampa\\/Southwest (FL)\"}]",
        "secondaryMarkets": null,
        "skills": "[{\"Skill\":\"RFI\"},{\"Skill\":\"HERS\"},{\"Skill\":\"ESTAR\"},{\"Skill\":\"QA QCCHECK\"}]"
    }
] 