export const TASK_DUMMY_DATA = [
    {
        "observationTaskId": 1782076,
        "taskName": "Tile Roof - Final Inspection",
        "organizationId": 3123,
        "organizationName": "Taylor Morrison - SW Florida",
        "siteId": 5032,
        "siteName": "09 ESP Azario 52-2022",
        "unitName": "Lot 7146",
        "streetAddress": "16419 ISOLA PL",
        "city": "Bradenton",
        "zipCode": "34211",
        "state": "FL",
        "assigneedId": 56354,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 9,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 1877458,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12720,
        "organizationName": "DR Horton - Tampa North (ST)",
        "siteId": 3144,
        "siteName": "Mangrove",
        "unitName": "DMAG 171/2",
        "streetAddress": "499 Mangrove Manor Dr",
        "city": "Apollo Beach",
        "zipCode": "33572",
        "state": "FL",
        "assigneedId": 100714,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 1877474,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12720,
        "organizationName": "DR Horton - Tampa North (ST)",
        "siteId": 3144,
        "siteName": "Mangrove",
        "unitName": "DMAG 172/2",
        "streetAddress": "497 MANGROVE MANOR DR.",
        "city": "Apollo Beach",
        "zipCode": "33572",
        "state": "FL",
        "assigneedId": 100714,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 1877477,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12720,
        "organizationName": "DR Horton - Tampa North (ST)",
        "siteId": 3144,
        "siteName": "Mangrove",
        "unitName": "DMAG 173/2",
        "streetAddress": "495 MANGROVE SHADE CIR",
        "city": "Apollo Beach",
        "zipCode": "33572",
        "state": "FL",
        "assigneedId": 100714,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 1877488,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12720,
        "organizationName": "DR Horton - Tampa North (ST)",
        "siteId": 3144,
        "siteName": "Mangrove",
        "unitName": "DMAG 174/2",
        "streetAddress": "493 MANGROVE SHADE CIR",
        "city": "Apollo Beach",
        "zipCode": "33572",
        "state": "FL",
        "assigneedId": 100714,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2600988,
        "taskName": "Confined Space",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601031,
        "taskName": "COVID 19 SAFETY INSPECTIOPN ",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 70,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601072,
        "taskName": "Electrical",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 18,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601114,
        "taskName": "Excavations",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601155,
        "taskName": "Fall Protection",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601196,
        "taskName": "Fire Protection",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 5,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601239,
        "taskName": "First Aid",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 6,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601288,
        "taskName": "Floors, Stairs, Walkways",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 21,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601331,
        "taskName": "Hoisting Equipment",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601372,
        "taskName": "Housekeeping",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 19,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601413,
        "taskName": "Ladders",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 16,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601454,
        "taskName": "Manlifts",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601495,
        "taskName": "Motorized Equipment",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 12,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601536,
        "taskName": "Occupational Health",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 17,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601579,
        "taskName": "Personal Protective Equipment",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601660,
        "taskName": "Posters & Signs",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 21,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601701,
        "taskName": "Powder Actuated Tools",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601742,
        "taskName": "Power Tools & Equipment",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601791,
        "taskName": "Safety Program",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601832,
        "taskName": "Scaffolding",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 12,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601873,
        "taskName": "Welding",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2601915,
        "taskName": "Wire Pull (Tugger) Equipment",
        "organizationId": 5171,
        "organizationName": "MSD Capital, L.P.",
        "siteId": 5360,
        "siteName": "The Naples Beach Club- Safety Audit",
        "unitName": "Site Safety Audit 22",
        "streetAddress": "",
        "city": "",
        "zipCode": "",
        "state": "",
        "assigneedId": 98274,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2660659,
        "taskName": "HERS - Final",
        "organizationId": 13397,
        "organizationName": "Mattamy Homes - Tampa/Sarasota (ST)",
        "siteId": 32295,
        "siteName": "Bonavie Cove Villas",
        "unitName": "BCV 181",
        "streetAddress": "6617 Upward Spring Place",
        "city": "Fort Myers",
        "zipCode": "33966",
        "state": "FL",
        "assigneedId": 100705,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2660668,
        "taskName": "HERS - Final",
        "organizationId": 13397,
        "organizationName": "Mattamy Homes - Tampa/Sarasota (ST)",
        "siteId": 32295,
        "siteName": "Bonavie Cove Villas",
        "unitName": "BCV 182",
        "streetAddress": "6619 Upward Spring Place",
        "city": "Fort Myers",
        "zipCode": "33966",
        "state": "FL",
        "assigneedId": 100705,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2664125,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 13210,
        "organizationName": "DR HORTON -West Central FL (WCFL)",
        "siteId": 2970,
        "siteName": "Hernando Spot Lots (WCFL)",
        "unitName": "HESP 25/46",
        "streetAddress": "1511 Piper Rd",
        "city": "Spring Hill",
        "zipCode": "34606",
        "state": "FL",
        "assigneedId": 100709,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2665419,
        "taskName": "FGBC Site Visit 2",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 38872,
        "siteName": "Tucker's Cove",
        "unitName": "TUCO 6327",
        "streetAddress": "14982 ANCHORAGE RD",
        "city": "Punta Gorda",
        "zipCode": "33982",
        "state": "FL",
        "assigneedId": 100983,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 20,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2665421,
        "taskName": "HERS - Final",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 38872,
        "siteName": "Tucker's Cove",
        "unitName": "TUCO 6327",
        "streetAddress": "14982 ANCHORAGE RD",
        "city": "Punta Gorda",
        "zipCode": "33982",
        "state": "FL",
        "assigneedId": 100983,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2665595,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 13210,
        "organizationName": "DR HORTON -West Central FL (WCFL)",
        "siteId": 2970,
        "siteName": "Hernando Spot Lots (WCFL)",
        "unitName": "HESP W100",
        "streetAddress": "7272 Apache Trail",
        "city": "Spring Hill",
        "zipCode": "34606",
        "state": "FL",
        "assigneedId": 100709,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2668246,
        "taskName": "FGBC Site Visit 2",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 38872,
        "siteName": "Tucker's Cove",
        "unitName": "TUCO 6563",
        "streetAddress": "15015 ANCHORAGE RD",
        "city": "Punta Gorda",
        "zipCode": "33982",
        "state": "FL",
        "assigneedId": 100983,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 20,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2668248,
        "taskName": "HERS - Final",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 38872,
        "siteName": "Tucker's Cove",
        "unitName": "TUCO 6563",
        "streetAddress": "15015 ANCHORAGE RD",
        "city": "Punta Gorda",
        "zipCode": "33982",
        "state": "FL",
        "assigneedId": 100983,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2668479,
        "taskName": "FGBC Site Visit 2",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 28039,
        "siteName": "Lorraine Lakes Villas",
        "unitName": "LOLV 454",
        "streetAddress": "5311 Crystal Harbor Cove",
        "city": "Bradenton",
        "zipCode": "34211",
        "state": "FL",
        "assigneedId": 100722,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 20,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2668481,
        "taskName": "HERS - Final",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 28039,
        "siteName": "Lorraine Lakes Villas",
        "unitName": "LOLV 454",
        "streetAddress": "5311 Crystal Harbor Cove",
        "city": "Bradenton",
        "zipCode": "34211",
        "state": "FL",
        "assigneedId": 100722,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2702006,
        "taskName": "FGBC Site Visit 2",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 28039,
        "siteName": "Lorraine Lakes Villas",
        "unitName": "LOLV 451",
        "streetAddress": "5405 Crystal Harbor Cove",
        "city": "Bradenton",
        "zipCode": "34211",
        "state": "FL",
        "assigneedId": 100722,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 20,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2702009,
        "taskName": "HERS - Final",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 28039,
        "siteName": "Lorraine Lakes Villas",
        "unitName": "LOLV 451",
        "streetAddress": "5405 Crystal Harbor Cove",
        "city": "Bradenton",
        "zipCode": "34211",
        "state": "FL",
        "assigneedId": 100722,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2738956,
        "taskName": "FGBC Site Visit 2",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 28039,
        "siteName": "Lorraine Lakes Villas",
        "unitName": "LOLV 0450",
        "streetAddress": "5409 Crystal Hbr Cv",
        "city": "Bradenton",
        "zipCode": "34211",
        "state": "FL",
        "assigneedId": 100722,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 20,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2738959,
        "taskName": "HERS - Final",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 28039,
        "siteName": "Lorraine Lakes Villas",
        "unitName": "LOLV 0450",
        "streetAddress": "5409 Crystal Hbr Cv",
        "city": "Bradenton",
        "zipCode": "34211",
        "state": "FL",
        "assigneedId": 100722,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2738967,
        "taskName": "FGBC Site Visit 2",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 28039,
        "siteName": "Lorraine Lakes Villas",
        "unitName": "LOLV 449",
        "streetAddress": "5413 Crystal Hbr Cv",
        "city": "Bradenton",
        "zipCode": "34211",
        "state": "FL",
        "assigneedId": 100722,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 20,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2738970,
        "taskName": "HERS - Final",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 28039,
        "siteName": "Lorraine Lakes Villas",
        "unitName": "LOLV 449",
        "streetAddress": "5413 Crystal Hbr Cv",
        "city": "Bradenton",
        "zipCode": "34211",
        "state": "FL",
        "assigneedId": 100722,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2740116,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 13416,
        "organizationName": "Kolter Homes, LLC (SW Florida) (ST)",
        "siteId": 39277,
        "siteName": "Woodland Preserve",
        "unitName": "WDPR 109",
        "streetAddress": "14451 Coastal Woodland LN",
        "city": "Parrish",
        "zipCode": "34219",
        "state": "FL",
        "assigneedId": 100719,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2743729,
        "taskName": "HERS - Final",
        "organizationId": 13397,
        "organizationName": "Mattamy Homes - Tampa/Sarasota (ST)",
        "siteId": 8307,
        "siteName": "Brightmore",
        "unitName": "BGHT 5",
        "streetAddress": "11535 MYAKKA BLUE DR",
        "city": "Venice",
        "zipCode": "34293",
        "state": "FL",
        "assigneedId": 100733,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2745589,
        "taskName": "HERS - Final",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 38873,
        "siteName": "Webbs Reserve",
        "unitName": "WBRS 6979",
        "streetAddress": "15010 Longs Ln",
        "city": "Punta Gorda",
        "zipCode": "33982",
        "state": "FL",
        "assigneedId": 100983,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2746105,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12950,
        "organizationName": "DR Horton - SW Florida (ST)",
        "siteId": 8788,
        "siteName": "Magnolia II TVs",
        "unitName": "MGTV 129/F1",
        "streetAddress": "20224 Camino Torcido Lp",
        "city": "North Fort Myers",
        "zipCode": "33917",
        "state": "FL",
        "assigneedId": 56394,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2750886,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12950,
        "organizationName": "DR Horton - SW Florida (ST)",
        "siteId": 39351,
        "siteName": "Bentley Crossing",
        "unitName": "DRBC 220",
        "streetAddress": "1243 Brumfield Xing",
        "city": "Fort Myers",
        "zipCode": "33905",
        "state": "FL",
        "assigneedId": 100705,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2754503,
        "taskName": "Tile Roof - Final Inspection",
        "organizationId": 3123,
        "organizationName": "Taylor Morrison - SW Florida",
        "siteId": 5035,
        "siteName": "09 ESP Azario GC 52-2022",
        "unitName": "Lot 6211",
        "streetAddress": "14950 contenta loop",
        "city": "Bradenton",
        "zipCode": "34211",
        "state": "FL",
        "assigneedId": 56354,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 9,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2769793,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12950,
        "organizationName": "DR Horton - SW Florida (ST)",
        "siteId": 39351,
        "siteName": "Bentley Crossing",
        "unitName": "DRBC 219",
        "streetAddress": "1249 BRUMFIELD CROSSING",
        "city": "Fort Myers",
        "zipCode": "33905",
        "state": "FL",
        "assigneedId": 100705,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2778917,
        "taskName": "Tile Roof - Final Inspection",
        "organizationId": 3123,
        "organizationName": "Taylor Morrison - SW Florida",
        "siteId": 5070,
        "siteName": "09 Skye Ranch AA 62-2022",
        "unitName": "Lot 5080",
        "streetAddress": "10160 Silent Night Ln",
        "city": "Sarasota",
        "zipCode": "34241",
        "state": "FL",
        "assigneedId": 56354,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 9,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2780769,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12950,
        "organizationName": "DR Horton - SW Florida (ST)",
        "siteId": 39351,
        "siteName": "Bentley Crossing",
        "unitName": "DRBC 126",
        "streetAddress": "1256 Brumfield Xing",
        "city": "Fort Myers",
        "zipCode": "33905",
        "state": "FL",
        "assigneedId": 100705,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2780785,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12950,
        "organizationName": "DR Horton - SW Florida (ST)",
        "siteId": 39351,
        "siteName": "Bentley Crossing",
        "unitName": "DRBC 127",
        "streetAddress": "1262 Brumfield Xing",
        "city": "Fort Myers",
        "zipCode": "33905",
        "state": "FL",
        "assigneedId": 100705,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2786021,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12979,
        "organizationName": "Taylor Morrison Homes - West Florida Division (ST)",
        "siteId": 7127,
        "siteName": "Esplanade @ BTI",
        "unitName": "EBTI 000412",
        "streetAddress": "15780 Derna ST",
        "city": "Naples",
        "zipCode": "34114",
        "state": "FL",
        "assigneedId": 56394,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2794983,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 13352,
        "organizationName": "Adams Homes - Spring Hill/Ocala (ST)",
        "siteId": 24596,
        "siteName": "Hidden Lakes",
        "unitName": "HDDL 17/C",
        "streetAddress": "7605 SW 103rd Loop",
        "city": "Ocala",
        "zipCode": "34476",
        "state": "FL",
        "assigneedId": 100727,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2796226,
        "taskName": "Code Blower Door ",
        "organizationId": 13352,
        "organizationName": "Adams Homes - Spring Hill/Ocala (ST)",
        "siteId": 24596,
        "siteName": "Hidden Lakes",
        "unitName": "HDDL 18/C",
        "streetAddress": "7613 SW 103rd Street Rd",
        "city": "Ocala",
        "zipCode": "34476",
        "state": "FL",
        "assigneedId": 100727,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 25,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2803802,
        "taskName": "Tile Roof - Final Inspection",
        "organizationId": 3123,
        "organizationName": "Taylor Morrison - SW Florida",
        "siteId": 5062,
        "siteName": "09 Skye Ranch AA TV-2022",
        "unitName": "Lot 5135",
        "streetAddress": "10249 Silent Night Ln",
        "city": "Sarasota",
        "zipCode": "34241",
        "state": "FL",
        "assigneedId": 56354,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 9,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2804495,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12979,
        "organizationName": "Taylor Morrison Homes - West Florida Division (ST)",
        "siteId": 7127,
        "siteName": "Esplanade @ BTI",
        "unitName": "EBTI 356",
        "streetAddress": "15831 Triesta LANE",
        "city": "Naples",
        "zipCode": "34114",
        "state": "FL",
        "assigneedId": 56394,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2804514,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12979,
        "organizationName": "Taylor Morrison Homes - West Florida Division (ST)",
        "siteId": 7127,
        "siteName": "Esplanade @ BTI",
        "unitName": "EBTI 346",
        "streetAddress": "15791 Triesta Lane",
        "city": "Naples",
        "zipCode": "34114",
        "state": "FL",
        "assigneedId": 56394,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2811488,
        "taskName": "Code Blower Door/Duct Blaster - ReInspection",
        "organizationId": 13397,
        "organizationName": "Mattamy Homes - Tampa/Sarasota (ST)",
        "siteId": 33154,
        "siteName": "Sunstone at Wellen Park 30",
        "unitName": "SAWP 206/22",
        "streetAddress": "12333 MEDITATION TRL",
        "city": "Venice",
        "zipCode": "34293",
        "state": "FL",
        "assigneedId": 100733,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2811575,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 13416,
        "organizationName": "Kolter Homes, LLC (SW Florida) (ST)",
        "siteId": 39277,
        "siteName": "Woodland Preserve",
        "unitName": "WDRD 132",
        "streetAddress": "14448 Woodland PRESERVE TR",
        "city": "Parrish",
        "zipCode": "34219",
        "state": "FL",
        "assigneedId": 100719,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2843720,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 13407,
        "organizationName": "Kolter Homes, LLC (Orlando)",
        "siteId": 39707,
        "siteName": "Cresswind Hammock Oaks",
        "unitName": "Lot 120",
        "streetAddress": "420 DOUGLAS HILL DR",
        "city": "Lady Lake",
        "zipCode": "32158",
        "state": "FL",
        "assigneedId": 100727,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2851959,
        "taskName": "Code Blower Door ",
        "organizationId": 13325,
        "organizationName": "Wade Jurney Homes (ST)",
        "siteId": 26992,
        "siteName": "Port Charlotte",
        "unitName": "PCHR 171805",
        "streetAddress": "1754 Torgerson St",
        "city": "Port Charlotte",
        "zipCode": "33952",
        "state": "FL",
        "assigneedId": 101720,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 25,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2852097,
        "taskName": "HERS - Final",
        "organizationId": 13397,
        "organizationName": "Mattamy Homes - Tampa/Sarasota (ST)",
        "siteId": 33154,
        "siteName": "Sunstone at Wellen Park 30",
        "unitName": "SAWP 248",
        "streetAddress": "12248 MEDITATION TRL",
        "city": "Venice",
        "zipCode": "34293",
        "state": "FL",
        "assigneedId": 100733,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2852153,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 13210,
        "organizationName": "DR HORTON -West Central FL (WCFL)",
        "siteId": 3156,
        "siteName": "Marion Spot Lots",
        "unitName": "DNPI 18/66",
        "streetAddress": "15055 SW 39th Cir",
        "city": "Ocala",
        "zipCode": "34473",
        "state": "FL",
        "assigneedId": 100727,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2852851,
        "taskName": "QC Check - ReInspection",
        "organizationId": 12785,
        "organizationName": "ResiBuilt LLC Florida (ST) ",
        "siteId": 39324,
        "siteName": "Wildwood Landing",
        "unitName": "WWLD 55",
        "streetAddress": "5243 Inglewood Drive",
        "city": "Wildwood",
        "zipCode": "34785",
        "state": "FL",
        "assigneedId": 100707,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 54,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2852879,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 13210,
        "organizationName": "DR HORTON -West Central FL (WCFL)",
        "siteId": 3156,
        "siteName": "Marion Spot Lots",
        "unitName": "MSPL 18/66",
        "streetAddress": "15055 SW 39th Circle",
        "city": "OCALA",
        "zipCode": "34473",
        "state": "FL",
        "assigneedId": 100727,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2853681,
        "taskName": "QC Check - ReInspection",
        "organizationId": 12785,
        "organizationName": "ResiBuilt LLC Florida (ST) ",
        "siteId": 39324,
        "siteName": "Wildwood Landing",
        "unitName": "WWLD 56",
        "streetAddress": "5247 Inglewood Drive",
        "city": "Wildwood",
        "zipCode": "34785",
        "state": "FL",
        "assigneedId": 100707,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 54,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2853705,
        "taskName": "QC Check",
        "organizationId": 13397,
        "organizationName": "Mattamy Homes - Tampa/Sarasota (ST)",
        "siteId": 33154,
        "siteName": "Sunstone at Wellen Park 30",
        "unitName": "SAWP 201",
        "streetAddress": "12301 Meditation Trl",
        "city": "Venice",
        "zipCode": "34293",
        "state": "FL",
        "assigneedId": 100733,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 54,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2853787,
        "taskName": "QC Check",
        "organizationId": 13397,
        "organizationName": "Mattamy Homes - Tampa/Sarasota (ST)",
        "siteId": 33154,
        "siteName": "Sunstone at Wellen Park 30",
        "unitName": "SAWP 203",
        "streetAddress": "12311 MEDITATION TRL",
        "city": "Venice",
        "zipCode": "34293",
        "state": "FL",
        "assigneedId": 100733,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 54,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2853801,
        "taskName": "QC Check",
        "organizationId": 13397,
        "organizationName": "Mattamy Homes - Tampa/Sarasota (ST)",
        "siteId": 33154,
        "siteName": "Sunstone at Wellen Park 30",
        "unitName": "SAWP 204",
        "streetAddress": "12317 MEDITATION TRL",
        "city": "Venice",
        "zipCode": "34293",
        "state": "FL",
        "assigneedId": 100733,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 54,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2853985,
        "taskName": "HERS - Final",
        "organizationId": 13397,
        "organizationName": "Mattamy Homes - Tampa/Sarasota (ST)",
        "siteId": 33376,
        "siteName": "Windwater",
        "unitName": "WDWT 203",
        "streetAddress": "5316 123rd Avenue E.",
        "city": "Parrish",
        "zipCode": "34219",
        "state": "FL",
        "assigneedId": 100719,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2858781,
        "taskName": "QC Check - ReInspection",
        "organizationId": 12785,
        "organizationName": "ResiBuilt LLC Florida (ST) ",
        "siteId": 39324,
        "siteName": "Wildwood Landing",
        "unitName": "WWLD 58",
        "streetAddress": "5255 Inglewood Drive",
        "city": "Wildwood",
        "zipCode": "34785",
        "state": "FL",
        "assigneedId": 100707,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 54,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2859136,
        "taskName": "QC Check - ReInspection",
        "organizationId": 12785,
        "organizationName": "ResiBuilt LLC Florida (ST) ",
        "siteId": 39324,
        "siteName": "Wildwood Landing",
        "unitName": "WWLD 60",
        "streetAddress": "5263 Inglewood Drive",
        "city": "Wildwood",
        "zipCode": "34785",
        "state": "FL",
        "assigneedId": 100707,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 54,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2861342,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12979,
        "organizationName": "Taylor Morrison Homes - West Florida Division (ST)",
        "siteId": 28662,
        "siteName": "Esplanade Lake Club",
        "unitName": "ESLC 796",
        "streetAddress": "18237 Terracina Drive",
        "city": "Fort Myers",
        "zipCode": "33913",
        "state": "FL",
        "assigneedId": 100705,
        "taskStatusId": 4,
        "taskStatusName": "Assigned",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2861759,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 13210,
        "organizationName": "DR HORTON -West Central FL (WCFL)",
        "siteId": 3156,
        "siteName": "Marion Spot Lots",
        "unitName": "MSPL 8/606",
        "streetAddress": "17497 SW 34th Court",
        "city": "OCALA",
        "zipCode": "34473",
        "state": "FL",
        "assigneedId": 100727,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2862270,
        "taskName": "HERS - Final",
        "organizationId": 12854,
        "organizationName": "Lennar Homes LLC - Tampa (ST)",
        "siteId": 2249,
        "siteName": "Angeline",
        "unitName": "ANGL 1E13",
        "streetAddress": "17225 Tortoise Crown Blvd",
        "city": "Land O' Lakes",
        "zipCode": "34638",
        "state": "FL",
        "assigneedId": 100710,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2868357,
        "taskName": "Code Blower Door/Duct Blaster - ReInspection",
        "organizationId": 13325,
        "organizationName": "Wade Jurney Homes (ST)",
        "siteId": 26992,
        "siteName": "Port Charlotte",
        "unitName": "PCHR 9941 ",
        "streetAddress": "9941 Calumet ",
        "city": "Port Charlotte",
        "zipCode": "33952",
        "state": "FL",
        "assigneedId": 101720,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2871369,
        "taskName": "FGBC Site Visit 1",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 11993,
        "siteName": "Babcock Flatwoods",
        "unitName": "BABF 4068",
        "streetAddress": "17955 Woodbine Way",
        "city": "Punta Gorda",
        "zipCode": "33982",
        "state": "FL",
        "assigneedId": 56370,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 13,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2871372,
        "taskName": "HERS - Thermal Bypass",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 11993,
        "siteName": "Babcock Flatwoods",
        "unitName": "BABF 4068",
        "streetAddress": "17955 Woodbine Way",
        "city": "Punta Gorda",
        "zipCode": "33982",
        "state": "FL",
        "assigneedId": 56370,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2871384,
        "taskName": "HERS - Final",
        "organizationId": 12854,
        "organizationName": "Lennar Homes LLC - Tampa (ST)",
        "siteId": 2249,
        "siteName": "Angeline",
        "unitName": "ANGL 37",
        "streetAddress": "10851 Ibis Brook Court",
        "city": "Land O Lakes",
        "zipCode": "34638",
        "state": "FL",
        "assigneedId": 100710,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2871853,
        "taskName": "Tile Roof - Dry-In, Flashing ",
        "organizationId": 6640,
        "organizationName": "Taylor Morrison - Tampa",
        "siteId": 5440,
        "siteName": "09 AL ESP North 62",
        "unitName": "Lot 254",
        "streetAddress": "11506 Campania Ter",
        "city": "Palmetto",
        "zipCode": "34221",
        "state": "FL",
        "assigneedId": 56354,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 9,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872287,
        "taskName": "Tile Roof - Dry-In, Flashing ",
        "organizationId": 3123,
        "organizationName": "Taylor Morrison - SW Florida",
        "siteId": 5036,
        "siteName": "09 ESP Azario GC 62-2022",
        "unitName": "Lot 6072",
        "streetAddress": "15225 contenta loop",
        "city": "Bradenton",
        "zipCode": "34211",
        "state": "FL",
        "assigneedId": 56354,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 9,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872331,
        "taskName": "Tile Roof - Dry-In, Flashing ",
        "organizationId": 3123,
        "organizationName": "Taylor Morrison - SW Florida",
        "siteId": 5032,
        "siteName": "09 ESP Azario 52-2022",
        "unitName": "Lot 5037",
        "streetAddress": "3667 Santa Caterina Blvd",
        "city": "Bradenton",
        "zipCode": "34211",
        "state": "FL",
        "assigneedId": 56354,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 9,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872477,
        "taskName": "HERS - Final",
        "organizationId": 12854,
        "organizationName": "Lennar Homes LLC - Tampa (ST)",
        "siteId": 2249,
        "siteName": "Angeline",
        "unitName": "ANGL 453",
        "streetAddress": "11143 Wishing Cloud Road",
        "city": "Land O Lakes",
        "zipCode": "34638",
        "state": "FL",
        "assigneedId": 100710,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872495,
        "taskName": "HERS - Final",
        "organizationId": 12854,
        "organizationName": "Lennar Homes LLC - Tampa (ST)",
        "siteId": 2249,
        "siteName": "Angeline",
        "unitName": "ANGL 0451",
        "streetAddress": "11135 Wishing Cloud Road",
        "city": "Land O Lakes",
        "zipCode": "34638",
        "state": "FL",
        "assigneedId": 100710,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872513,
        "taskName": "HERS - Final",
        "organizationId": 12854,
        "organizationName": "Lennar Homes LLC - Tampa (ST)",
        "siteId": 2249,
        "siteName": "Angeline",
        "unitName": "ANGL 455",
        "streetAddress": "11155 Wishing Cloud Road",
        "city": "Land O Lakes",
        "zipCode": "34638",
        "state": "FL",
        "assigneedId": 100710,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872539,
        "taskName": "HERS - Final",
        "organizationId": 12854,
        "organizationName": "Lennar Homes LLC - Tampa (ST)",
        "siteId": 2249,
        "siteName": "Angeline",
        "unitName": "ANGL 452",
        "streetAddress": "11139 Wishing Cloud Road",
        "city": "Land O Lakes",
        "zipCode": "34638",
        "state": "FL",
        "assigneedId": 100710,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872557,
        "taskName": "HERS - Final",
        "organizationId": 12854,
        "organizationName": "Lennar Homes LLC - Tampa (ST)",
        "siteId": 2249,
        "siteName": "Angeline",
        "unitName": "ANGL 454",
        "streetAddress": "11147 Wishing Cloud Road",
        "city": "Land O Lakes",
        "zipCode": "34638",
        "state": "FL",
        "assigneedId": 100710,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 79,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872594,
        "taskName": "Code Compliance Plus - Thermal",
        "organizationId": 12950,
        "organizationName": "DR Horton - SW Florida (ST)",
        "siteId": 39251,
        "siteName": "Central Parc",
        "unitName": "CNTP 315/1",
        "streetAddress": "5155 SCHUBERT TRL",
        "city": "North Port",
        "zipCode": "34287",
        "state": "FL",
        "assigneedId": 101720,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 30,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872614,
        "taskName": "Code Blower Door ",
        "organizationId": 12854,
        "organizationName": "Lennar Homes LLC - Tampa (ST)",
        "siteId": 3180,
        "siteName": "Mirada (TPA)",
        "unitName": "MRAD 2327",
        "streetAddress": "31698 Griffin Sands Lane",
        "city": "San Antonio",
        "zipCode": "33576",
        "state": "FL",
        "assigneedId": 100714,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 25,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872635,
        "taskName": "HERS - Thermal Bypass",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 39245,
        "siteName": "Tucker's Cove Townhomes",
        "unitName": "TUTO 6817",
        "streetAddress": "14891 WHITE PEARL RD",
        "city": "Punta Gorda",
        "zipCode": "33982",
        "state": "FL",
        "assigneedId": 56370,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872645,
        "taskName": "HERS - Thermal Bypass",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 39245,
        "siteName": "Tucker's Cove Townhomes",
        "unitName": "TUTO 6816",
        "streetAddress": "14895 WHITE PEARL RD",
        "city": "Punta Gorda",
        "zipCode": "33982",
        "state": "FL",
        "assigneedId": 56370,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872654,
        "taskName": "HERS - Thermal Bypass",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 39245,
        "siteName": "Tucker's Cove Townhomes",
        "unitName": "TUTO 6818",
        "streetAddress": "14887 WHITE PEARL RD",
        "city": "Punta Gorda",
        "zipCode": "33982",
        "state": "FL",
        "assigneedId": 56370,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872671,
        "taskName": "HERS - Thermal Bypass",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 39245,
        "siteName": "Tucker's Cove Townhomes",
        "unitName": "TUTO 6815",
        "streetAddress": "14899 WHITE PEARL RD",
        "city": "Punta Gorda",
        "zipCode": "33982",
        "state": "FL",
        "assigneedId": 56370,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872683,
        "taskName": "HERS - Thermal Bypass",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 39245,
        "siteName": "Tucker's Cove Townhomes",
        "unitName": "TUTO 6819",
        "streetAddress": "14883 WHITE PEARL RD",
        "city": "Punta Gorda",
        "zipCode": "33982",
        "state": "FL",
        "assigneedId": 56370,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872692,
        "taskName": "HERS - Thermal Bypass",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 39245,
        "siteName": "Tucker's Cove Townhomes",
        "unitName": "TUTO 6820",
        "streetAddress": "14879 WHITE PEARL RD",
        "city": "Punta Gorda",
        "zipCode": "33982",
        "state": "FL",
        "assigneedId": 56370,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872701,
        "taskName": "HERS - Thermal Bypass",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 39245,
        "siteName": "Tucker's Cove Townhomes",
        "unitName": "TUTO 6821",
        "streetAddress": "14875 WHITE PEARL RD",
        "city": "Punta Gorda",
        "zipCode": "33982",
        "state": "FL",
        "assigneedId": 56370,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872720,
        "taskName": "HERS - Thermal Bypass",
        "organizationId": 12989,
        "organizationName": "Lennar Homes - SW Florida (ST)",
        "siteId": 39245,
        "siteName": "Tucker's Cove Townhomes",
        "unitName": "TUTO 6822",
        "streetAddress": "14871 WHITE PEARL RD",
        "city": "Punta Gorda",
        "zipCode": "33982",
        "state": "FL",
        "assigneedId": 56370,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872749,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12720,
        "organizationName": "DR Horton - Tampa North (ST)",
        "siteId": 37507,
        "siteName": "Westwood",
        "unitName": "WSTV 124/2",
        "streetAddress": "17227 Bigleaf Mahogany Ln",
        "city": "Land O' Lakes",
        "zipCode": "34638",
        "state": "FL",
        "assigneedId": 100709,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872758,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12720,
        "organizationName": "DR Horton - Tampa North (ST)",
        "siteId": 37507,
        "siteName": "Westwood",
        "unitName": "WSTV 125/2",
        "streetAddress": "17233 Bigleaf Mahogany Ln",
        "city": "Land O' Lakes",
        "zipCode": "34638",
        "state": "FL",
        "assigneedId": 100709,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872767,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12720,
        "organizationName": "DR Horton - Tampa North (ST)",
        "siteId": 37507,
        "siteName": "Westwood",
        "unitName": "WSTV 126/2",
        "streetAddress": "17237 Bigleaf Mahogany Ln",
        "city": "Land O' Lakes",
        "zipCode": "34638",
        "state": "FL",
        "assigneedId": 100709,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2872776,
        "taskName": "Code Blower Door/Duct Blaster",
        "organizationId": 12720,
        "organizationName": "DR Horton - Tampa North (ST)",
        "siteId": 37507,
        "siteName": "Westwood",
        "unitName": "WSTV 127/2",
        "streetAddress": "17271 Bigleaf Mahogany Ln",
        "city": "Land O' Lakes",
        "zipCode": "34638",
        "state": "FL",
        "assigneedId": 100709,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 59,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2873159,
        "taskName": "HERS - Thermal Bypass",
        "organizationId": 13397,
        "organizationName": "Mattamy Homes - Tampa/Sarasota (ST)",
        "siteId": 33154,
        "siteName": "Sunstone at Wellen Park 30",
        "unitName": "SWAP 359",
        "streetAddress": "12233 NEW TRANQUILITY PATH",
        "city": "Venice",
        "zipCode": "34293",
        "state": "FL",
        "assigneedId": 100733,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 34,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    },
    {
        "observationTaskId": 2873314,
        "taskName": "ENERGY STAR - Thermal Bypass ",
        "organizationId": 12950,
        "organizationName": "DR Horton - SW Florida (ST)",
        "siteId": 23823,
        "siteName": "Lehigh Spot Lots",
        "unitName": "LSOT 5/128",
        "streetAddress": "2509 28th St SW",
        "city": "Lehigh Acres",
        "zipCode": "33976",
        "state": "FL",
        "assigneedId": 56377,
        "taskStatusId": 5,
        "taskStatusName": "Scheduled",
        "scheduleDate": "2025-01-29T00:00:00",
        "duration": 35,
        "market": "Tampa/Southwest (FL)",
        "skills": null
    }
]

